# Generated by Django 3.2.4 on 2021-07-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Administradores',
        ),
    ]
