# Generated by Django 3.2.4 on 2021-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_problemas_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemas',
            name='curso_id',
        ),
    ]
