# Generated by Django 3.0 on 2021-05-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemas',
            name='curso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servidor.Cursos'),
            preserve_default=False,
        ),
    ]
